### ISSUE TITLE
OAI-PMH: Configure custom sets (e.g. for OpenAIRE)

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#1931]
Create a feature mechanism to load oai sets from an `oai_sets.yaml` containing the below:

Based on the [OpenAIRE guidelines](https://guidelines.openaire.eu/en/latest/data/use_of_oai_pmh.html):

```yaml
- name: "OpenAIRE Data"
  spec: "openaire_data" 
  search_pattern: "resource_type.type:dataset"
```

You can find an example on how we load [users](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/users.py) in invenio-rdm-records!
