### ISSUE TITLE
Vocabularies: improve error handling missing vocabularies (e.g. parent resource types)

### ISSUE THREAD

**Issue by sepiida** [inveniosoftware/invenio-app-rdm#2013]
Package version (if known): RDM 9.1

## Describe the bug
User attempted to publish a restricted metadata-only record (JSON attached), navigates to her dashboard, and receives a HTTP 500 server error on the '.../api/user/records' call. The 'Oops! Something went wrong while fetching results.' message is displayed. Additionally the new record does not appear for any user when using the search bar, though searches complete successfully and without producing errors.

## Steps to Reproduce
1. Add metadata-only restricted record. 
2. Navigate to the dashboard.
3. Error message and HTTP 500 api/user/records error encountered.

...
![err_stack1](https://user-images.githubusercontent.com/14008992/212433237-31ae6e7a-909b-4354-85da-fe7caf530bfe.PNG)
![inv_stacktrace2](https://user-images.githubusercontent.com/14008992/212433243-cba9b4f8-fb72-4675-bc7c-3d94592e0cc2.PNG)
[rdm_rec_json.txt](https://github.com/inveniosoftware/invenio-app-rdm/files/10415923/rdm_rec_json.txt)

**Comment by ppanero** [comment]
**Important**

This happens with custom resource types, in particular:

```
- id: dataset-datastore
  icon: table
  props:
    csl: dataset
    datacite_general: Dataset
    datacite_type: ''
    schema.org: https://schema.org/Dataset
    subtype: datastore
    type: dataset
  title:
    en: Data Store
  tags:
    - depositable
    - linkable
```

Needs to be added to `resource_types.yaml` before running setup/fixtures.
