### ISSUE TITLE
Vocabularies: 'id' Field Requirement for Names Schema in InvenioRDM

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-app-rdm#2545]
Package version (if known): V12dev > 25

## Describe the bug
The 'id' field requirement within the names schema in InvenioRDM is either an intentional change or a bug. 
 When manually adding names through instance setup or command line, these entries lack an 'id' field leading to validation error that was not the case before V12dev25.

## The Question: 
- Should we update the requirement for an `id` field in the names schema so we  update names ex: [here](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/app_data/vocabularies/names.yaml)  and update the documentation [here](https://github.com/inveniosoftware/docs-invenio-rdm/blob/master/docs/customize/vocabularies/names.md#data-model) by adding their id fields

- Or It's an oversight in handling vocabulary that needs correction.

## Steps to Reproduce
1- on a fresh v12 latest using `app_data/vocabularies/names.yaml`
```yaml
- affiliations:
  - name: University of Zurich
  - name: Humboldt University of Berlin
  - name: Kaiser Wilhelm Institute for Physics
  family_name: Einstein # <-- This will not be imported
  given_name: Albert
  identifiers:
  - identifier: gnd:118529579
    scheme: gnd
- affiliations:
  - name: University of Cambridge
  - name: California Institute of Technology
  - name: University of Oxford
  family_name: Hawking
  given_name: Stephen
  id: 0000-0002-9079-593X # <-- this will be imported
  identifiers:
  - identifier: https://orcid.org/0000-0002-9079-593X
    scheme: orcid
```
2- Import names using the command: 
`invenio vocabularies import --vocabulary names --filepath app_data/vocabularies-future.yaml`

3- Observe the behavior: names with an 'id' field (e.g., Stephen Hawking) are imported, while those without an 'id' (e.g., Albert Einstein) are not with validation error.

## Expected behavior
Names should be imported consistently, regardless of the presence of an 'id' field in the YAML file.

## Screenshots (if applicable)
This is before and after adding `id`field to each names vocabularies:
![Screenshot 2023-12-02 152923](https://github.com/inveniosoftware/invenio-app-rdm/assets/36583694/d48d2d5b-ce16-4e89-a5ae-3519b97429c7)

## Additional context
This problem seems to have arisen in versions after V12dev25. specifically, after this big refactor:
https://github.com/inveniosoftware/invenio-vocabularies/commit/ba8d3c632de625a29206e4a369a7468fe5c1b2e1

I did not test other ways of importing names like  ORCiD public dataset or other ways...
